### ISSUE TITLE
Fix position of reorder changes

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#107]
The reorder view doesn't take the added and removed rows into account. Therefore the lines are not drawn correctly.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24461133/89a2af86-14a0-11e7-8807-64d963b8a112.png)

**Comment by thinkh** [comment]
Done in taco_server.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24462179/a1b24dcc-14a3-11e7-8d6b-60da82245e12.png)

**Comment by mstreit** [comment]
why is the highlighted item in the diff heatmap not connected with the orange connection line?
