### ISSUE TITLE
Heat map data is loaded but not displayed

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#11]
Select a copy number dataset first and then select one or two dots from the timeline. The image for the according heatmap is loaded form the server, but the canvas element doesn't display the image data. 

![missing_heatmap](https://cloud.githubusercontent.com/assets/5851088/19197321/7d92a454-8cb9-11e6-955a-723325d916b5.png)

I assume that this is an issue from the [HeatMapImageRenderer class](https://github.com/Caleydo/taco/issues/4#issuecomment-251123689)? However, I couldn't figure out what exactly the problem is, because I don't get an error message.

@sgratzl Can you please have a look what the issue is with the Caleydo heatmap renderer? 

P.S.: With small matrices, such as the TaCo demo datasets the Canvas renderer works (probably because  the HeatMapCanvasRenderer class is used).

**Comment by sgratzl** [comment]
I guess the issue is that the canvas is too large for the browser. Try using a more intelligent initial scaling depending on the current data size.
