### ISSUE TITLE
Create Vistory 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#110]
For the camera-ready version we should create vistory links for our usage scenarios figures.

Missing pieces:
- [x] Selection of change type buttons must be reflected in URL hash
- [x] Selection within the heatmaps must be reflected in URL hash
- [x] [Create vistories.org URL](https://github.com/Caleydo/vistories_website/tree/master/_vistories)
- [x] Add URL to papers

**Comment by mstreit** [comment]
oh yes, that would be nice. and that's we we create CLUE!

**Comment by thinkh** [comment]
We can have a light version without CLUE 😉

**Comment by thinkh** [comment]
The light version, i.e. just app deeplinks in the paper, is done.
