### ISSUE TITLE
Slider for content change legend

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#114]
Implement a slider for content changes as in TACO v1.

![grafik](https://cloud.githubusercontent.com/assets/5851088/24551532/1c2d5080-1623-11e7-965e-e71d20b65f25.png)

**Comment by thinkh** [comment]
Implemented using the [jQuery UI slider](https://jqueryui.com/slider/#range).

![7b1964d3-e32f-4cab-a1d2-67b74c345fac](https://user-images.githubusercontent.com/5851088/27483050-14e4e142-5824-11e7-9272-9aafe9e446b0.gif)

**Comment by ngehlenborg** [comment]
Just came across this in Slack: you might want to add some explanation to that. What does a content change of "-1" mean? Or a content change of "0.34"?
