### ISSUE TITLE
Calculate distance between circles on the timeline

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#12]
- items in timeline.updateItems enthalten alle zeitpunkte (sollten auch sortiert sein)
- mit d3.pairs erstellst du immer zwei paare https://github.com/d3/d3-3.x-api-reference/blob/master/Arrays.md#d3_pairs [[t1, t2], [t2, t3], ...]
- das neue array durchlaufen und pair[0].time mit pair[1].time verwenden um die difference zu berechnen und diese als abstand zwischen den kreisen nehmen http://momentjs.com/docs/#/displaying/difference/

**Comment by NChristina** [comment]
Bug -> only when loading dataset "taco_server" or "tcga_sampled" 

d3.js:670 Error: <circle> attribute cx: Expected length, "NaN".

**Comment by thinkh** [comment]
How do I reproduce the error? Just opening the datasets?

**Comment by NChristina** [comment]
yes, just loading the specific dataset "taco_server" or "tcga_sampled"

**Comment by thinkh** [comment]
TaCo test data sets have no inherent time aspect (in comparision to TCGA data). This is the reason why `d.time` is undefined and causes an error when you want to get the `cx` value. I set a fixed value of 60 if `d.time` is undefined.
