### ISSUE TITLE
Add link to taco.caleydo.org to about dialog.

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taco#120]

**Comment by thinkh** [comment]
See related issue https://github.com/phovea/phovea_ui/issues/41

**Comment by thinkh** [comment]
The link is set in the package.json. Once the PRs https://github.com/phovea/phovea_ui/pull/42 and https://github.com/phovea/generator-phovea/pull/123 are merged, we have to re-deploy the app again. Then the homepage link is visible in the about dialog. Close this ticket afterwards.

**Comment by thinkh** [comment]
Done.

![image](https://user-images.githubusercontent.com/5851088/36546577-1295b88e-17ec-11e8-8eaf-7403437b297f.png)
