### ISSUE TITLE
The second layer does not show the aggregated visualization in Chrome

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taco#121]
* Release number or git hash: latest
* Web browser version and OS:  Chrome
* Environment (local or deployed): deployed

![image](https://user-images.githubusercontent.com/4129755/33671879-14cd45a2-daa9-11e7-8719-f573a7e46cc8.png)

**Comment by thinkh** [comment]
It seems to be a browser caching problem. Disabling/Clearing the cache fixes the problem as workaround.

**Comment by mstreit** [comment]
OK, that worked, thanks.
