### ISSUE TITLE
Show 2D Ratio Chart on timeline

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#13]

**Comment by NChristina** [comment]
Todo´s
- positioning svg between time points 
- scaling bars in the svg -> logarithmic scale?

**Comment by NChristina** [comment]
internal server error when loading "taco_server" or "tcga_sampled"

**Comment by thinkh** [comment]
I fixed the internal server error,  by removing datasets from index.json where no corresponding csv file exists.

**Comment by NChristina** [comment]
ToDO Resizing Window
first narrower bars  then hide bars, if the bar width is too narrow

**Comment by NChristina** [comment]
Closed #13
