### ISSUE TITLE
Logo is not displayed correctly

### ISSUE THREAD

**Issue by dvvanessastoiber** [Caleydo/taco#147]
* Release number or git hash: b5fb0763d391bbe5d42d34c1f4f7695ace06838a
* Web browser version and OS: Chrome 81, Linux
* Environment (local or deployed): both

### Steps to reproduce

1. Open https://taco.caleydoapp.org/
2. Click on `i` button in the navigation bar

### Observed behavior
* Logo (SVG) on the bottom left is not visible
![image](https://user-images.githubusercontent.com/52395160/80342678-d8956d00-8864-11ea-814f-693c7df8e850.png)

* this issue is likely to be related with webpack loaders

### Expected behavior
* Logo is shown correctly

**Comment by thinkh** [comment]
Seems to be resolved in the current version.

![grafik](https://user-images.githubusercontent.com/5851088/100725425-4fc74c80-33c4-11eb-947f-225580207004.png)
