### ISSUE TITLE
Implement tooltips for circles and bar chart

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#27]
- [x] Get data for the tooltip 
- [x] Create tooltip to the specific element (on-hover or mouseover)

**Comment by doomsayer2** [comment]
Works already for the circles.

**Comment by doomsayer2** [comment]
Bars also added

**Comment by thinkh** [comment]
@NChristina @doomsayer2 Should I check something here? Otherwise if it's working, you can go ahead and close the ticket.
