### ISSUE TITLE
Select circles in timeline

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#4]
As the links from the list, the circles should be selectable, too

**Comment by NChristina** [comment]
```
heatmap.ts:371 Uncaught TypeError: Cannot read property 'getContext' of null
HeatMapImageRenderer.redrawImpl @ heatmap.ts:371
HeatMapImageRenderer.redraw @ heatmap.ts:365
(anonymous function) @ heatmap.ts:577
image.onload @ heatmap.ts:429
```

if clicking two circles in the timeline to compare and open the heatmap

**Comment by NChristina** [comment]
![bildschirmfoto 2017-01-09 um 13 17 33](https://cloud.githubusercontent.com/assets/18003747/21766263/97335144-d66d-11e6-981a-819ab0eed8ee.png)
