### ISSUE TITLE
Update diff heatmap

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#47]
The diff heatmap is not updated according to the selected changes (at the moment only the bars are updated)
![image](https://cloud.githubusercontent.com/assets/18003747/22937274/6830fbee-f2d8-11e6-9387-cb4c131e1151.png)

**Comment by thinkh** [comment]
Might be resolved automatically with the new layout (#51).

**Comment by mstreit** [comment]
@thinkh, we can close this one, right?

**Comment by thinkh** [comment]
Yes, it's done.
