### ISSUE TITLE
Align changes in the 2d Ratio Histogramm

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#48]
Just hiding the unselected changes is incorrect. Compare the first screenshot with all changes to the second without the content changes. The visual representation shows over 50% additions which is not correct. You need to update the visualizations.
![image](https://cloud.githubusercontent.com/assets/18003747/22937327/8d03b844-f2d8-11e6-846b-f316c8c907f4.png)

**Comment by NChristina** [comment]
New calculation when hide/show particular change

**Comment by thinkh** [comment]
Duplicate of #49 --> close this.
