### ISSUE TITLE
Implement new layout of Taco

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#51]
![bildschirmfoto 2017-02-21 um 07 40 00](https://cloud.githubusercontent.com/assets/18003747/23153453/ff02723e-f808-11e6-81e4-308f7caead8a.png)

**Comment by NChristina** [comment]
First level: stacked bar chart positioned on the top of the circles (Table) 
Second level: Rectangle with onboarding text (please select two timepoints in the timeline...) 
Open 2D Ratio when selecting two specific time points. 
Third level: Rectangle for Source Table, Diff Table and Destination Table  
Button "Show Detail" - opening Source & Destination Heatmap and DiffHeatmap

**Comment by thinkh** [comment]
Done.
