### ISSUE TITLE
Implement Reorder Change DiffHeatmap

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#52]
reorder und merge change

**Comment by NChristina** [comment]
interface element for hide/show reorder or merge change
(no representation of reorder or merge change simultaneously in the diff heatmap)

**Comment by thinkh** [comment]
Check if rows/colums that are re-ordered are also contained in add/removed structural changes or if they are excluded from added/removed changes.

**Comment by thinkh** [comment]
Since we don't have merge changes in our paper datasets I will not implement the merge functionality for now.

**Comment by thinkh** [comment]
> Check if rows/colums that are re-ordered are also contained in add/removed structural changes or if they are excluded from added/removed changes.

Reordered changes are only counted for union cells/rows, i.e. that added or removed rows/columns are counted separately.

**Comment by thinkh** [comment]
Implemented as slope graphs for row changes.

![taggle_slope-graphs](https://cloud.githubusercontent.com/assets/5851088/24308075/e437952a-10c6-11e7-9e53-65ac478788c5.png)
