### ISSUE TITLE
Switching 2D histogram does not work

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#54]
### Steps to reproduce

1. Install and run TaCo
2. Click on the grouped bar to open the 2D ratio
3. Select a different bar chart to switch to another 2D ratio

### Observed behavior

![taco_2d-histogram_open_behavior](https://cloud.githubusercontent.com/assets/5851088/23399514/c97437c2-fda0-11e6-83e6-1de98bd9e515.gif)

### Expected behavior
* The 2D Ratio should not close when switching, it should remain open and only close if clicking the grouped bar again

**Comment by NChristina** [comment]
Can we close this issue, as it is deprecated with the new layout??

**Comment by thinkh** [comment]
Yes.
