### ISSUE TITLE
Show source/destination column ids at top and bottom of diff heatmap

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#57]
In order to show changes in column direction we have to show the column header for source and destination table at the top and bottom of the diff heatmap.

**Comment by NChristina** [comment]
![image](https://cloud.githubusercontent.com/assets/18003747/23401407/df442754-fda7-11e6-83e3-5454e72388f6.png)

**Comment by thinkh** [comment]
This is obsolete with https://github.com/Caleydo/taco/issues/102
