### ISSUE TITLE
Internal Server Error on timeline

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#59]
Error occurs only by Taco Change output and taco merge input 
![errors_1](https://cloud.githubusercontent.com/assets/13848511/23501205/43274f76-ff33-11e6-9cc2-23f2f04a149d.PNG)

**Comment by mstreit** [comment]
@NChristina Is this still an issue?

**Comment by mstreit** [comment]
Close for now. Re-open if problem occurs again.
