### ISSUE TITLE
Add ratio bars to timeline

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#6]
- [ ] Send request to server for two time steps (lazy loading)
- [ ] Show loading animation while waiting for request to finish
- [ ] Replace animation with result of ratio calculation

**Comment by thinkh** [comment]
@NChristina I refactored the code with commit https://github.com/Caleydo/taco/commit/f4f0fa72ee842388367e199a6861e136f0b3e27d a bit. The bars are now positioned between their corresponding circles and inside the same SVG element.

However, the solution looks bad, because of resizing the SVG, but I describe that in #10. For now it looks like that.

![taco_timeline](https://cloud.githubusercontent.com/assets/5851088/20144907/6877eee0-a69e-11e6-8f34-5337fcd0fc67.PNG)

The problem is that the bars might be wider than the available space between two circles. We have to find a solution for that problem.

**Comment by NChristina** [comment]
![bildschirmfoto 2017-01-09 um 13 16 45](https://cloud.githubusercontent.com/assets/18003747/21766239/7e64178e-d66d-11e6-8734-705ae6fc35e3.png)
![bildschirmfoto 2017-01-09 um 13 16 51](https://cloud.githubusercontent.com/assets/18003747/21766240/7e67cfc8-d66d-11e6-8b53-4299492b5ab5.png)
