### ISSUE TITLE
Add reorder and merge button to the filter bar

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#62]
Add two new buttons to the filter bars in the header for reorder and merge change

**Comment by thinkh** [comment]
Since we won't implement merge changes (https://github.com/Caleydo/taco/issues/52#issuecomment-284166460), we only need the reorder button.

**Comment by thinkh** [comment]
Done.

![taco_reorder-button](https://cloud.githubusercontent.com/assets/5851088/23899780/bf77941e-08b6-11e7-840a-d60bba35e99c.png)
