### ISSUE TITLE
Hide/Show changes in the diffHeatmap

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#64]
Hide/Show Changes in the diffHeatmap in the detail view

**Comment by mstreit** [comment]
Is this still valid? From the description I don't know what is meant here.

**Comment by thinkh** [comment]
The diff heatmap should adapt to the selection of change types in the filter bar at the top.

**Comment by thinkh** [comment]
Done.

![taco_diff-heatmap-changes](https://cloud.githubusercontent.com/assets/5851088/23959617/ebb9b922-09a5-11e7-8e7b-d278ac8d2bf4.gif)
