### ISSUE TITLE
Position bars over the later time point?

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#76]
At the moment the bars are positioned over the earlier timestep. It looks strange when there is no diff between 2008 and 2012 (last time point).

![taco_bar-chart-alignment-fixed](https://cloud.githubusercontent.com/assets/5851088/23898929/5fe1cdf6-08b3-11e7-88f0-6e5bd39e13cf.png)

I suggest to move the bars the later of the two time points, e.g. over 2012.

**Comment by mstreit** [comment]
or in between the time points with small splines connecting the bar and two associated time points?

**Comment by thinkh** [comment]
With #74 I positioned them exactly on tick of the axis time point.
