### ISSUE TITLE
Diff table does not resize

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taco#82]
![image](https://cloud.githubusercontent.com/assets/4129755/23941763/68ed620e-096a-11e7-8311-6eead19f680a.png)

**Comment by doomsayer2** [comment]
I also made it possible to resize and redraw the diffheatmap, see branch **feature_StylingChanges** but sometimes the event triggers too often and the previous diff heatmap isnt removed....
You should look over it after I made a pull request.

**Comment by thinkh** [comment]
@doomsayer2 Thanks. Please file a new PR that I can review.

**Comment by thinkh** [comment]
Fixed
