### ISSUE TITLE
Meta box layout

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taco#83]
I suggest to reduce the width of the meta boxes and also center the text

![image](https://cloud.githubusercontent.com/assets/4129755/23941818/92dd453e-096a-11e7-949a-fad109086d53.png)

**Comment by thinkh** [comment]
![taco_meta-box-layout](https://cloud.githubusercontent.com/assets/5851088/23957557/fbcb1528-099f-11e7-98e2-499b13880d75.png)
