### ISSUE TITLE
Timeline out of sync with bars after resize

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taco#84]
![image](https://cloud.githubusercontent.com/assets/4129755/23941976/0cc9b7ce-096b-11e7-91ae-a8fbcf352609.png)

**Comment by doomsayer2** [comment]
I fixed the current timeline resize method, as it was called not appropriate. Still the bars are not completely matching but better.

**feature_StylingChanges**

**Comment by thinkh** [comment]
@doomsayer2 Please file a new PR that I can review. Thanks.

**Comment by thinkh** [comment]
Fixed
